{% set name = "llvmlite" %}
{% set version = "0.40.0a1" %}
{% set sha256 = "7f4faa22f7ae702c54bf6331e85676950a14dcfe50c790a64793c330016681cd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gmarkall/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [py<37]
  script_env:
    - PY_VCRUNTIME_REDIST

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make                   # [unix]
  host:
    - python
    - setuptools
    - llvmdev 11.1.*
    - llvm 11.1.*
    - zlib
    - vs2015_runtime  # [win]
  run:
    - python
    - vs2015_runtime  # [win]

test:
  imports:
    - llvmlite
    - llvmlite.binding
  commands:
    - python -m llvmlite.tests

about:
  home: http://llvmlite.pydata.org
  license: BSD-2-Clause
  license_file: LICENSE
  summary: A lightweight LLVM python binding for writing JIT compilers.
  doc_url: http://llvmlite.pydata.org/
  dev_url: https://github.com/numba/llvmlite

extra:
  recipe-maintainers:
    - jakirkham
    - souravsingh
    - marcelotrevisani
    - xhochy
    - mbargull
